sudo: true

stages:
  - test
  - deploy

language: node_js
node_js: '8'

services:
  - docker

install:
  - npm install npm@^5

cache:
  directories:
  - ~/.npm
  - node_modules

jobs:
  include:
    - stage: test
      env: 
        - DOCKER_COMPOSE_VERSION=2.3
        - NODE_ENV=test
      script: npm run dctest:up