sudo: true

stages:
  - test
  - deploy

language: node_js
node_js: '8'

services:
  - docker

install:
  - npm install npm@^5

cache:
  directories:
  - ~/.npm
  - node_modules

jobs:
  include:
    - stage: test
      env: DOCKER_COMPOSE_VERSION=2.3
      script: cd scripts && ./test.sh