version: "2.3"

services:

  api:
    build:
      context: .
    image: molecular-microservices-blog-api
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 4000
    links:
      - nats
      - redis
    depends_on:
      - nats
      - redis
    ports:
      - 4000:4000
    command: npm run test
    volumes:
      - .:/opt/app

  users:
    build:
      context: .
    image: molecular-microservices-blog-users
    env_file: docker-compose.env
    environment:
      SERVICES: users
    links:
      - nats
      - redis
    depends_on:
      - nats
      - redis
      - api
    volumes:
      - .:/opt/app


  posts:
    build:
      context: .
    image: molecular-microservices-blog-posts
    env_file: docker-compose.env
    environment:
      SERVICES: posts
    links:
      - nats
      - redis
    depends_on:
      - nats
      - redis
      - api
    volumes:
      - .:/opt/app

  nats:
    image: nats

  redis:
    image: redis